server.port: 8081
spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 애플리케이션 실행 시점에 테이블, 엔티티를 다 지우고 다시 생성
    properties:
      hibernate:
#        show_sql: true --> print 를 통해 보임
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug # sql 이 다 보임 -> 로고를 통해 보임
    org.hibernate.type : trace